### ISSUE TITLE
Landing Page Updates

### ISSUE THREAD

**Issue by oreHGA** [NEUROFUSIONInc/fusion#139]
- Include gradient on the header
- 'About' is still a notion link. Need a web page on fusion website for that.
- 'Contact' - give some other social media handles. Not just open an email editor.
- Add 'Terms of Use' page

**Comment by peoray** [comment]
hey @oreHGA is this still a valid issue?

**Comment by oreHGA** [comment]
Once we get the next PR merged, these should be addressed

**Comment by peoray** [comment]
also there's no contributing guide. might be a good idea to create one given there are different products
