### ISSUE TITLE
Onboarding flow on the web

### ISSUE THREAD

**Issue by oreHGA** [NEUROFUSIONInc/fusion#157]
Welcome users into the app & guide them to understanding how to user the explorer
- [x] Modal with details similar to #73 
- [x]  Profile Page showing whether user is on Fusion Premium subscription - https://usefusion.app/profile

**Comment by peoray** [comment]
can you provide more information @oreHGA

**Comment by oreHGA** [comment]
> can you provide more information @oreHGA 

Hey @peoray do you have a specific question you'd like answered about it?

**Comment by oreHGA** [comment]
We basically needs a modal that comes up when a person signs in to Fusion for the first time telling them about 

- what they can do with it (brain recordings during cognitive experiments, respond to prompts on mobile...)
- how fusion handles their data (anonymous assigned identities with no email required, data stored locally)

**Comment by peoray** [comment]
ah I see then, I'll look into it

**Comment by abena07** [comment]
@oreHGA do you have a link to a figma for this like you do for the mobile?

**Comment by oreHGA** [comment]
hey @abena07 ! tagged you in the figma sketch... we use components in [the frontend package](https://github.com/NEUROFUSIONInc/fusion/tree/master/frontend/src/components) to build it into the site

**Comment by abena07** [comment]
@oreHGA alright then, checked it out and will send my concerns on discord

**Comment by abena07** [comment]
@oreHGA made a pr for the onboarding flow on web

**Comment by oreHGA** [comment]
Thank you for working on this @abena07 ! Just merged it in :)

**Comment by abena07** [comment]
🫡
