### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by peoray** [NEUROFUSIONInc/fusion#177]
As a newcomer to this repo, I have no idea how to go about ensuring fusion apps and clients work well on my local machine. This would make contributing to the project difficult and uninteresting for anyone looking to contribute!

**Comment by oreHGA** [comment]
Thank you for creating this! Curious, what questions did you have top of mind?

I've also been planning to record a video about the different projects in the repo

**Comment by peoray** [comment]
I don't have any questions per se. I just need to understand how to install the different apps and run them. Do I need any API key or command, etc. Basically how to get from 0-1 and make sure everything runs smoothly


for the react native app, what apps or software do I need on my local machine. same goes for other clients too

you can maybe have a contribution folder with each client as a file, so mobile_app.md or whatever, etc, if there's any general config, that can go in a global.md file or something like that. this is just a suggestion

**Comment by oreHGA** [comment]
Interesting suggestion.. will add it to the documentation rewrite I'm working on. I tried to have at least a readme.md for all the folders but might be missing some

In the meantime, I've tagged you in #175 with a link to the readme for getting started for with the nextjs app. Please ping me on discord when you're working on this, happy to hop on a call to make the process smoother.

I'll keep this issue active and update it as we add more relevant documentation for contribution.

**Comment by oreHGA** [comment]
Getting started for development on: 

The web client: https://github.com/NEUROFUSIONInc/fusion/tree/master/neurofusion/next-client
The mobile app: https://github.com/NEUROFUSIONInc/fusion/tree/master/fusionMobile

**Comment by oreHGA** [comment]
Closing this, our repo is now up to date on how to contribute. See the readme in each folder for more details on setup
