### ISSUE TITLE
Allow users to sign in with the same nostr account 

### ISSUE THREAD

**Issue by oreHGA** [NEUROFUSIONInc/fusion#189]
Currently when a person signs in to Fusion with nostr we auto generate an npub & nsec... login.form.ts

The challenge though is that the private key is not saved so the user cannot sign in again. What we need to do is

- [x] save the private key after generation in the local storage
- [x] update the /account page to also allow the user to copy and save they private key somewhere
- [x] when on the login page, allow a user to enter the privatekey to sign in just like a password
- [x] support signing in with nos2x for people that are advanced and already manage private keys

**Comment by okjodom** [comment]
skipping task number 2 "update the /account page to also allow the user to copy and save they private key somewhere"
