### ISSUE TITLE
Improve prompt creating & edits when a quest is being created

### ISSUE THREAD

**Issue by abena07** [NEUROFUSIONInc/fusion#223]
- essentially we are trying to simulate the experience on mobile where a user can add prompts to a quest in the most human way

- [x] replacing the json format with a single modal that will guide a user to populate quests with prompts
- [x] details of the change: inputs like description of a prompt, time to get a prompt and what nots
- [x] extras: the user should be able to edit, and add more prompts and potentially delete a prompt form a quest

**Comment by abena07** [comment]
@oreHGA what do you think about the description, also
-  will we allow users to delete prompts from a quest?
-  does a user have a limit to the number of prompts to add to a quest?

**Comment by oreHGA** [comment]
@abena07 yes, the person creating the quest can delete or include an unlimited number of prompts

**Comment by abena07** [comment]
alright!

**Comment by abena07** [comment]
@oreHGA i dunno what i am missing but i may need help with debugging why 

[ ] saving of prompts after refresh does not work
[ ]  prompts are not specific to quests

**Comment by oreHGA** [comment]
@abena07 I reviewed the draft and added comments to the PR... once we get the prompt config in the right format it'll handle the first two errors

**Comment by abena07** [comment]
okay, if i follow do i need to pull the changes added? because i don't see any comments. what i see is commits

**Comment by oreHGA** [comment]
Oh my bad, for some reason they were stuck in pending mode..can you try checking again now?

**Comment by abena07** [comment]
alright i see them now, you made some changes right? i’m guessing i will pull from there and continue working.
