### ISSUE TITLE
fix an edgecase for the onboarding modal

### ISSUE THREAD

**Issue by abena07** [NEUROFUSIONInc/fusion#228]
when a user navigates to analysis or quests and returns they should not see the onboarding modal when they navigate back to playground

**Comment by abena07** [comment]
@oreHGA i kinda missed this and will pick it up later to fix it

**Comment by oreHGA** [comment]
Thanks for flagging! Setting the flag to false by default fixes this. When the component loads, there's a check for whether it should be presented to the person or not. [See code snippet](https://github.com/NEUROFUSIONInc/fusion/blob/6a099e6ce00fb64e45e66e18b67b4e6a6378226a/frontend/src/pages/playground.tsx#L15C1-L23C10)
