### ISSUE TITLE
include activitywatch as a data source for screentime data

### ISSUE THREAD

**Issue by oreHGA** [NEUROFUSIONInc/fusion#42]
- [ ] add fusion to allowed urls that can fetch from local activitywatch
   - [ ] enable CORS
- [ ] make fetch calls from browser using https://github.com/ActivityWatch/aw-client-js

**Comment by oreHGA** [comment]
Hey @ErikBjare , I tried using the `aw-client-js` to list the active buckets but I'm getting a CORS error as the response
<img width="1482" alt="Screenshot 2023-12-05 at 6 56 13 PM" src="https://github.com/NEUROFUSIONInc/fusion/assets/13490968/86aa26a6-1148-403f-9b8f-c7497d7c1681">

Code snippet I used after installing the library:

```
    const awClient = new AWClient("fusionClient");
    awClient.getBuckets().then((buckets) => {
      console.log(buckets);
    });
  };
  ```
  
Is there somewhere I need to set Fusion's domain was an an allowed origin from ActivityWatch?

**Comment by ErikBjare** [comment]
@oreHGA Yes, see: https://github.com/ActivityWatch/aw-webui#cors

Basically you can add allowed CORS origins in the config files. Not the most user-friendly experience, but somewhat easy to do.

**Comment by oreHGA** [comment]
Thanks @ErikBjare this worked (had to restart activitywatch for it to take effect)

We'll add the steps for this in the integration instructions:

```
Windows: %LocalAppData%\activitywatch\activitywatch

macOS: ~/Library/Application\ Support/activitywatch/

Linux: ~/.config/activitywatch, or the path defined by the $XDG_CONFIG_HOME environment variable.
```

`cors_origins = "https://localhost:3000"`

(in prod it'll be https://usefusion.app)

- Restart ActivityWatch app  (they'll only have to do this once)

**Comment by oreHGA** [comment]
This is what we want to call afterwards to fetch screentime history - https://github.com/ActivityWatch/aw-client-js/blob/39868c71e48a23193aed77167894917ea423f812/src/aw-client.ts#L316

**Comment by oreHGA** [comment]
@abena07 here's where we're tracking activity watch integrations in the web client

**Comment by abena07** [comment]
@oreHGA okay! will like to be more clear on a few things so will schedule a call for this weekend.

**Comment by oreHGA** [comment]
eventually, we'd want to eventually make a PR to activitywatch settings page that allows the user to update the allowed domains from here: http://localhost:5600/#/settings
